FROM microsoft/dotnet:2.0.0-sdk AS build
WORKDIR /app
COPY front.csproj /app/front.csproj
RUN dotnet restore
COPY . /app
RUN dotnet publish -c Release -o /built

FROM microsoft/aspnetcore:2.0.0
EXPOSE 80
ENV ASPNETCORE_URLS http://+:80
COPY --from=build /built /app
WORKDIR /app
ENTRYPOINT ["dotnet", "front.dll"]